name: smat_code_x
description: A cool and aesthetic code reviewer app.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  flutter_syntax_view: ^4.0.0
  flutter_highlight: ^0.7.0
  highlight: ^0.7.0
  flutter_svg: ^2.0.7
  animated_text_kit: ^4.2.2
  lottie: ^2.6.0
  flutter_animate: ^4.2.0
  glassmorphism: ^3.0.0
  shared_preferences: ^2.2.2
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - images/
